class Autogenerated {
  double latitude;
  double longitude;
  List<String> recycling;
  Autogenerated({this.latitude, this.longitude, this.recycling});
  Autogenerated.fromJson(Map<String, dynamic> json) {
    latitude = json['latitude'];
    longitude = json['longitude'];
    recycling = json['recycling'].cast<String>();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['recycling'] = this.recycling;
    return data;
  }
}
